name: first-wf
on: workflow_dispatch
jobs:
  first-wf:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Goodbye!"
